default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: rails
  pool: 5

development:
  <<: *default
  database: backbone_frontend_development
  password: rails_user

test:
  <<: *default
  database: backbone_frontend_test
  password: rails_user


production:
  <<: *default
  database: backbone_frontend_production
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
